class exercise_model {
  String? exercise_hedphoto;
  String? exercise_hedTitle;
  List<String>? exercise_photo;
  List<String>? exercise_Title;
  exercise_model(
      {this.exercise_Title,
      this.exercise_hedphoto,
      this.exercise_photo,
      this.exercise_hedTitle});
  static List<exercise_model> fullBody = [
    exercise_model(
      exercise_hedTitle: 'تمارين للجسم بكامله',
      exercise_hedphoto: 'assets/images/allbody.jpg',
      exercise_photo: [
        'assets/images/burpees.gif',
        'assets/images/dumbbelloverheadrainbow.gif',
        'assets/images/flutterkicksquats1.gif',
        'assets/images/kneeandelbowpressup.gif',
        'assets/images/pilateshundred.gif',
        'assets/images/plankkickthroughs.gif',
        'assets/images/reverselungeshoulderpress.gif',
        'assets/images/runinplace.gif',
        'assets/images/scissorskier.gif',
        'assets/images/shrimpsquat.gif',
        'assets/images/skiabs.gif',
        'assets/images/standingcrisscrosscrunches.gif',
        'assets/images/standingsidebend.gif',
      ],
      exercise_Title: [
        'burpees',
        'dumbbell overhead rainbow',
        'flutter kick squats ',
        'knee and elbow press up',
        'pilates hundred',
        'plank kick throughs',
        'Reverse lunge shoulder press',
        'Run in place',
        'Scissor skier',
        'shrimp squat',
        'ski abs',
        'standing criss cross crunches',
        'Standing side bend',
      ],
    ),
    exercise_model(
      exercise_hedTitle: 'تمارين للذراعين والصدر ',
      exercise_hedphoto: 'assets/images/arm.jpg',
      exercise_photo: [
        'assets/images/chestFly.gif',
        'assets/images/declinepushup.gif',
        'assets/images/pushups.gif',
        'assets/images/spidermanpushups.gif',
        'assets/images/bicepscurl.gif',
        'assets/images/inchworm.gif',
        'assets/images/kettlebellswing.gif',
        'assets/images/lateralraise.gif',
        'assets/images/sideplank.gif',
        'assets/images/supermanwitharmextension.gif',
        'assets/images/tricepskickback.gif',
      ],
      exercise_Title: [
        'Chest Fly',
        'decline push up',
        'push ups',
        'spiderman push ups ',
        'Biceps curl',
        'Inchworm',
        'Kettlebell swing',
        'Lateral raise.gif',
        'Plank shoulder taps',
        'Side plank',
        'Superman with arm extension',
        'Triceps kickback',
      ],
    ),
    exercise_model(
      exercise_hedTitle: 'تمارين للبطن  ',
      exercise_hedphoto: 'assets/images/stomach.jpg',
      exercise_photo: [
        'assets/images/bicyclecrunches.gif',
        'assets/images/frogbridge.gif',
        'assets/images/frogcrunches.gif',
        'assets/images/obliquevcrunch.gif',
        'assets/images/reversecrunches.gif',
        'assets/images/situp.gif',
        'assets/images/sprinterchrunch.gif',
        'assets/images/toetouch.gif',
      ],
      exercise_Title: [
        'bicycle crunches',
        'frog bridge',
        'frog crunches',
        'oblique v crunch ',
        'reverse crunches',
        'sit up',
        'sprinter chrunch',
        'toe touch',
      ],
    ),
    exercise_model(
      exercise_hedTitle: 'تمارين للرجل  ',
      exercise_hedphoto: 'assets/images/leg.jpg',
      exercise_photo: [
        'assets/images/backleglifts.gif',
        'assets/images/bandedstep-outs.gif',
        'assets/images/hipbridges.gif',
        'assets/images/jumpsquats.gif',
        'assets/images/kickcrunch.gif',
        'assets/images/romaniandeadlifts.gif',
        'assets/images/sideleglifts.gif',
        'assets/images/squatsidekick.gif',
        'assets/images/step-ups.gif',
      ],
      exercise_Title: [
        'Back leg lifts',
        'Banded step-outs',
        'Hip bridges',
        'jump squats ',
        'Kick crunch',
        'Romanian deadlifts',
        'Side leg lifts',
        'squat side kick',
        'Step-ups',
      ],
    ),
  ];
}
